import { COLORS } from "./colors.ts";
import type { TConsoleStyles } from "./css.ts";

const TW_LIGHT = 300;
const TW_REGULAR = 400;
const TW_DARK = 700;

export const SHORTCUTS = {
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
  slateLight: { color: COLORS.slate[TW_LIGHT] },
  slate: { color: COLORS.slate[TW_REGULAR] },
  slateDark: { color: COLORS.slate[TW_DARK] },
  grayLight: { color: COLORS.gray[TW_LIGHT] },
  gray: { color: COLORS.gray[TW_REGULAR] },
  grayDark: { color: COLORS.gray[TW_DARK] },
  zincLight: { color: COLORS.zinc[TW_LIGHT] },
  zinc: { color: COLORS.zinc[TW_REGULAR] },
  zincDark: { color: COLORS.zinc[TW_DARK] },
  neutralLight: { color: COLORS.neutral[TW_LIGHT] },
  neutral: { color: COLORS.neutral[TW_REGULAR] },
  neutralDark: { color: COLORS.neutral[TW_DARK] },
  stoneLight: { color: COLORS.stone[TW_LIGHT] },
  stone: { color: COLORS.stone[TW_REGULAR] },
  stoneDark: { color: COLORS.stone[TW_DARK] },
  redLight: { color: COLORS.red[TW_LIGHT] },
  red: { color: COLORS.red[TW_REGULAR] },
  redDark: { color: COLORS.red[TW_DARK] },
  orangeLight: { color: COLORS.orange[TW_LIGHT] },
  orange: { color: COLORS.orange[TW_REGULAR] },
  orangeDark: { color: COLORS.orange[TW_DARK] },
  amberLight: { color: COLORS.amber[TW_LIGHT] },
  amber: { color: COLORS.amber[TW_REGULAR] },
  amberDark: { color: COLORS.amber[TW_DARK] },
  yellowLight: { color: COLORS.yellow[TW_LIGHT] },
  yellow: { color: COLORS.yellow[TW_REGULAR] },
  yellowDark: { color: COLORS.yellow[TW_DARK] },
  limeLight: { color: COLORS.lime[TW_LIGHT] },
  lime: { color: COLORS.lime[TW_REGULAR] },
  limeDark: { color: COLORS.lime[TW_DARK] },
  greenLight: { color: COLORS.green[TW_LIGHT] },
  green: { color: COLORS.green[TW_REGULAR] },
  greenDark: { color: COLORS.green[TW_DARK] },
  emeraldLight: { color: COLORS.emerald[TW_LIGHT] },
  emerald: { color: COLORS.emerald[TW_REGULAR] },
  emeraldDark: { color: COLORS.emerald[TW_DARK] },
  tealLight: { color: COLORS.teal[TW_LIGHT] },
  teal: { color: COLORS.teal[TW_REGULAR] },
  tealDark: { color: COLORS.teal[TW_DARK] },
  cyanLight: { color: COLORS.cyan[TW_LIGHT] },
  cyan: { color: COLORS.cyan[TW_REGULAR] },
  cyanDark: { color: COLORS.cyan[TW_DARK] },
  skyLight: { color: COLORS.sky[TW_LIGHT] },
  sky: { color: COLORS.sky[TW_REGULAR] },
  skyDark: { color: COLORS.sky[TW_DARK] },
  blueLight: { color: COLORS.blue[TW_LIGHT] },
  blue: { color: COLORS.blue[TW_REGULAR] },
  blueDark: { color: COLORS.blue[TW_DARK] },
  indigoLight: { color: COLORS.indigo[TW_LIGHT] },
  indigo: { color: COLORS.indigo[TW_REGULAR] },
  indigoDark: { color: COLORS.indigo[TW_DARK] },
  violetLight: { color: COLORS.violet[TW_LIGHT] },
  violet: { color: COLORS.violet[TW_REGULAR] },
  violetDark: { color: COLORS.violet[TW_DARK] },
  purpleLight: { color: COLORS.purple[TW_LIGHT] },
  purple: { color: COLORS.purple[TW_REGULAR] },
  purpleDark: { color: COLORS.purple[TW_DARK] },
  fuchsiaLight: { color: COLORS.fuchsia[TW_LIGHT] },
  fuchsia: { color: COLORS.fuchsia[TW_REGULAR] },
  fuchsiaDark: { color: COLORS.fuchsia[TW_DARK] },
  pinkLight: { color: COLORS.pink[TW_LIGHT] },
  pink: { color: COLORS.pink[TW_REGULAR] },
  pinkDark: { color: COLORS.pink[TW_DARK] },
  roseLight: { color: COLORS.rose[TW_LIGHT] },
  rose: { color: COLORS.rose[TW_REGULAR] },
  roseDark: { color: COLORS.rose[TW_DARK] },
} satisfies Record<string, TConsoleStyles>;
